# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_projectRbindings_wrappers", use_symbols = TRUE, package_name = "projectRbindings")

#' @usage NULL
#' @useDynLib projectRbindings, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
hello_world <- function() .Call(wrap__hello_world)

use_fancy <- function() .Call(wrap__use_fancy)


# nolint end
